### ISSUE TITLE
bytestring and bytestring-builder dependencies do not match

### ISSUE THREAD

**Issue by mdibaiee** [ekmett/semigroups#74]
hey,

your package requires `bytestring (>=0.9 && <0.10.4)` and `bytestring-builder(>=0.10.4 && <1)` in case of enabled `bytestring-builder` flag and `bytestring-builder` requires `bytestring (>=0.9 && <0.10.2 || >=0.10.4)`, thus it's not possible to use `bytestring >=0.10.4` along with your package. If `bytestring-builder` supports it, I think you can, too.

**Comment by hvr** [comment]
Ok, in machine-friendly terms, we're talking about

```
    if flag(bytestring-builder) -- NB: this is an automatic flag!
        bytestring (>=0.9 && <0.10.4)
        bytestring-builder (>=0.10.4 && <1)
    else
        bytestring (>=0.10.4 && <1)
```

When using automatic flags, it's desirable to discriminate on something in a mutually exclusive way, in order for the solver to make a clear choice. The pattern above encodes the pseudo-code logic of

```
  if version(bytestring) < 0.10.4 -- this decision point gets labelled by the flag `bytestring-builder`
     build-depends: bytestring-builder >= 0.10.4
```

More importantly, this ensures that any kind of API conditionality is at least detectable via  the `MIN_VERSION_bytestring()` macro. Otherwise it'd be possible to end up in a situation where we can't detect if `semigroups` was depending on `bytestring-builder` or not, since we can't access flag settings of dependencies via `cabal_macros.h`

**Comment by ekmett** [comment]
Closing this as as I understand it we no longer have a bytestring-builder dependency. Feel free to re-open if I misunderstood.
