### ISSUE TITLE
Docs for 1.18.2 busted on hackage (not the usual problem)

### ISSUE THREAD

**Issue by slpopejoy** [ekmett/semigroups#78]
http://hackage.haskell.org/package/semigroups-0.18.2 has docs for Data.Semigroup.Generic but not for anything else. I don't know if this project uploads it's own docs?

**Comment by hvr** [comment]
@slpopejoy This is the result of `semigroups` exposing modules conditionally based on what `base` exports; and since the docs were generated with GHC 8, the only module exposed is the Data.Semigroup.Generic one. In the future, Hackage may add support for reexported modules (and `semigroups` may make use of them), then Data.Semigroup would be a symlink to `base`'s Data.Semigroup module.

**Comment by slpopejoy** [comment]
So what do we do about broken links in Hayoo etc? A search for `NonEmpty` (which you're saying is in base now?) results in a broken link.

**Comment by slpopejoy** [comment]
Even more busted on Hoogle, a search for `NonEmpty` doesn't find base or semigroups.

This is a serious issue.

**Comment by gbaz** [comment]
For the time being, it seems correct the docs aren't there -- I think that it may be better to ask hoogle/hayoo to update their dbs to ghc 8, so they can find the modules where they've lived since ghc 8's release -- in base.

**Comment by slpopejoy** [comment]
OK opened issues on hayoo, hoogle
